from datetime import datetime
from pydantic import BaseModel, Field
from typing import Dict, List, Any, Optional


class TicketSubmission(BaseModel):
    """
    Schema for initial ticket submission by the user.
    """
    title: str = Field(..., description="The title of the support ticket", min_length=3, max_length=255)
    description: str = Field(..., description="The detailed explanation of the issue in the ticket", min_length=10)
    environment: Optional[str] = Field(default=None, description="Environment details such as OS, browser, app version")
    steps_to_reproduce: Optional[List[str]] = Field(default=None, description="Step-by-step instructions to reproduce the issue")
    expected_result: Optional[str] = Field(default=None, description="What the user expected to happen")
    actual_result: Optional[str] = Field(default=None, description="What actually happened")
    priority: Optional[str] = Field(default=None, description="Ticket priority: Low, Medium, High, Critical")
    severity: Optional[str] = Field(default=None, description="Ticket severity: Low, Medium, High, Critical")
    module_name: Optional[str] = Field(default=None, description="Application module/component affected")
    fix_version: Optional[str] = Field(default=None, description="Version in which the fix will be released")
    affected_version: Optional[str] = Field(default=None, description="Version where the bug was found")
    due_date: Optional[str] = Field(default=None, description="Target fix date (YYYY-MM-DD)")
    client: Optional[str] = Field(default=None, description="Client or customer affected")
    epic: Optional[str] = Field(default=None, description="Epic or feature group this ticket belongs to")
    sprint: Optional[str] = Field(default=None, description="Sprint this ticket is assigned to")
    attachments: Optional[List[str]] = Field(default=None, description="Base64-encoded image attachments for OCR analysis")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Optional extra metadata associated with the ticket")
    submitted_by: Optional[str] = Field(default=None, description="Name/ID of the user who submitted the ticket")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of submission")


class TicketUpdate(BaseModel):
    """All fields are optional — only provided ones are updated."""
    title: Optional[str] = Field(default=None, min_length=3, max_length=255)
    description: Optional[str] = Field(default=None, min_length=10)
    environment: Optional[str] = None
    steps_to_reproduce: Optional[List[str]] = None
    expected_result: Optional[str] = None
    actual_result: Optional[str] = None
    priority: Optional[str] = None
    severity: Optional[str] = None
    module_name: Optional[str] = None
    fix_version: Optional[str] = None
    affected_version: Optional[str] = None
    due_date: Optional[str] = None
    client: Optional[str] = None
    epic: Optional[str] = None
    sprint: Optional[str] = None
    status: Optional[str] = Field(default=None, description="Manual status transition: 'closed' or 'pending'")


class AuditResult(BaseModel):
    """
    Schema for the audit results generated by the Audit Agent.
    """
    score: float = Field(..., description="Calculated ticket quality score (e.g., from 0.0 to 100.0)", ge=0.0, le=100.0)
    passed: bool = Field(..., description="True if the ticket meets quality guardrails/threshold")
    findings: List[str] = Field(default_factory=list, description="List of issues or positive observations identified during the audit")
    missing_information: List[str] = Field(default_factory=list, description="List of specific information/details missing from the ticket description")
    requires_clarification: bool = Field(default=False, description="True if the ticket requires asking clarifying questions to the user")


class ClarificationQuestion(BaseModel):
    """
    Schema representing a question generated by the Question Agent for missing info.
    """
    question_id: str = Field(..., description="Unique identifier for the clarification question")
    field_or_topic: str = Field(..., description="The missing information topic or specific field (e.g., environment, steps_to_reproduce)")
    question_text: str = Field(..., description="The question generated by the Question Agent for the user")


class ClarificationResponse(BaseModel):
    """
    Schema representing the response/answer given by the user for a question.
    """
    question_id: str = Field(..., description="Identifier matching the clarification question being responded to")
    answer_text: str = Field(..., description="The clarification response text provided by the user")


class RewrittenTicket(BaseModel):
    """
    Schema representing the polished ticket generated by the Rewrite Agent.
    """
    rewritten_title: str = Field(..., description="The professional, clear, rewritten title of the ticket")
    rewritten_description: str = Field(..., description="The structured, comprehensive, rewritten description of the ticket")
    improvements_made: List[str] = Field(default_factory=list, description="List of changes and improvements implemented by the Rewrite Agent")


class DuplicateResult(BaseModel):
    """
    Schema for checking and matching ticket duplication.
    """
    is_duplicate: bool = Field(..., description="True if a duplicate ticket is found in the vector database")
    duplicate_ticket_id: Optional[str] = Field(default=None, description="ID of the duplicate ticket if one is found")
    similarity_score: Optional[float] = Field(default=None, description="Similarity score between current and duplicate ticket (0.0 to 1.0)")
    matching_explanation: Optional[str] = Field(default=None, description="Explanation detailing why the tickets are considered duplicates")


class EvaluationResult(BaseModel):
    """
    Schema representing the final quality score validation and notes.
    """
    final_score: float = Field(..., description="The final evaluated quality score of the ticket post-rewriting", ge=0.0, le=100.0)
    met_criteria: bool = Field(..., description="True if the rewritten ticket meets the criteria checklists")
    evaluation_notes: str = Field(..., description="Detailed notes and criteria evaluations from the Evaluation Agent")


class WorkflowResponse(BaseModel):
    """
    Schema representing the state and output of the Supervisor Agent coordination workflow.
    """
    status: str = Field(..., description="Workflow status: 'processing', 'needs_clarification', 'duplicate_found', 'completed', or 'failed'")
    ticket_id: Optional[int] = Field(default=None, description="The internal database ID of the ticket")
    score: Optional[float] = Field(default=None, description="Ticket completeness score from 0.0 to 100.0 when available")
    questions: Optional[List[ClarificationQuestion]] = Field(default=None, description="Questions generated if clarification is needed")
    duplicate_result: Optional[DuplicateResult] = Field(default=None, description="Duplication results if a duplicate is found")
    rewritten_ticket: Optional[RewrittenTicket] = Field(default=None, description="The rewritten ticket content if completed")
    github_issue_url: Optional[str] = Field(default=None, description="HTML URL of the created GitHub issue")
    github_issue_number: Optional[int] = Field(default=None, description="GitHub issue number if created")

