import { useState, useCallback, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  Plus, Inbox, CheckCircle2, AlertTriangle, XCircle, Loader2,
  Send, ExternalLink, ClipboardList, AlertCircle, GitBranch,
  Paperclip, X, Eye, FileText, Pencil, RotateCcw, Archive, RefreshCcw,
  Users, TicketCheck, TrendingUp, Clock, CheckCheck, AlertOctagon,
} from 'lucide-react';
import './DashboardPage.css';

const API_BASE = '/api/v1';

const COLUMNS = [
  { id: 'inprogress', label: 'IN PROGRESS', statuses: ['pending', 'needs_clarification', 'processing'], hint: 'Being reviewed, awaiting answers, or processing' },
  { id: 'done',       label: 'DONE',        statuses: ['completed'],                                    hint: 'Published to GitHub' },
  { id: 'failed',     label: 'FAILED',      statuses: ['failed', 'closed', 'duplicate_found'],         hint: 'Failed, closed, or duplicate detected' },
];

const STATUS_BADGE = {
  pending:             { cls: 'badge-neutral', label: 'Pending' },
  processing:          { cls: 'badge-info',    label: 'Processing' },
  needs_clarification: { cls: 'badge-warning', label: 'Needs Info' },
  completed:           { cls: 'badge-success', label: 'Done' },
  duplicate_found:     { cls: 'badge-error',   label: 'Duplicate' },
  failed:              { cls: 'badge-error',   label: 'Failed' },
  closed:              { cls: 'badge-neutral', label: 'Closed' },
};

const PRIORITY_OPTIONS = ['Low', 'Medium', 'High', 'Critical'];
const SEVERITY_OPTIONS = ['Low', 'Medium', 'High', 'Critical'];

function Badge({ status }) {
  const m = STATUS_BADGE[status] || { cls: 'badge-neutral', label: status };
  return <span className={`badge ${m.cls}`}>{m.label}</span>;
}

function parseApiError(e) {
  if (!e) return 'Unknown error';
  if (typeof e.detail === 'string') return e.detail;
  if (Array.isArray(e.detail)) return e.detail.map(x => x.msg).join(', ');
  return e.message || JSON.stringify(e);
}

const EMPTY_FORM = {
  title: '', description: '', environment: '', stepsRaw: '',
  expected_result: '', actual_result: '',
  priority: 'Medium', severity: 'Medium',
  module_name: '', fix_version: '', affected_version: '',
  due_date: '', client: '', epic: '', sprint: '',
};

// ─── Chatbot component ────────────────────────────────────────────────────────
// Zero extra API calls: questions already generated by backend.
// Shows them one-by-one as chat bubbles, validates locally, submits batch.
function ClarificationChat({ ticket, token, onDone, onError }) {
  const questions = ticket.questions || [];
  const [messages, setMessages] = useState(() => {
    // Seed the first AI question
    if (questions.length === 0) return [];
    return [{ role: 'ai', text: questions[0].question_text, qIdx: 0 }];
  });
  const [currentIdx, setCurrentIdx] = useState(0);
  const [inputVal, setInputVal] = useState('');
  const [answers, setAnswers] = useState({});   // { question_id: answer_text }
  const [submitting, setSubmitting] = useState(false);
  const [allDone, setAllDone] = useState(false);
  const bottomRef = useRef(null);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  const MIN_ANSWER_LEN = 4;

  const sendMessage = () => {
    const text = inputVal.trim();
    if (!text) return;

    const q = questions[currentIdx];

    // Add user bubble
    const userMsg = { role: 'user', text };
    setMessages(prev => [...prev, userMsg]);
    setInputVal('');

    // Validate answer length — re-ask locally (no API call)
    if (text.length < MIN_ANSWER_LEN) {
      setTimeout(() => {
        setMessages(prev => [...prev, {
          role: 'ai',
          text: `That answer seems too short. Could you please provide more detail about "${q.field_or_topic}"?`,
          qIdx: currentIdx,
        }]);
      }, 400);
      return;
    }

    // Accept answer
    const newAnswers = { ...answers, [q.question_id]: text };
    setAnswers(newAnswers);

    const nextIdx = currentIdx + 1;
    if (nextIdx < questions.length) {
      // Ask next question
      setCurrentIdx(nextIdx);
      setTimeout(() => {
        setMessages(prev => [...prev, { role: 'ai', text: questions[nextIdx].question_text, qIdx: nextIdx }]);
      }, 400);
    } else {
      // All answered
      setTimeout(() => {
        setMessages(prev => [...prev, {
          role: 'ai',
          text: 'Thank you! I have all the information I need. Click Submit Answers to proceed.',
        }]);
        setAllDone(true);
      }, 400);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); }
  };

  const handleSubmit = async () => {
    setSubmitting(true);
    try {
      const payload = Object.keys(answers).map(qid => ({ question_id: qid, answer_text: answers[qid] }));
      const res = await fetch(`${API_BASE}/tickets/${ticket.id}/clarify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(parseApiError(await res.json()));
      onDone();
    } catch (err) {
      onError(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  if (questions.length === 0) return null;

  const progress = Math.round((Object.keys(answers).length / questions.length) * 100);

  return (
    <div className="chat-container">
      <div className="chat-progress-bar">
        <div className="chat-progress-fill" style={{ width: `${progress}%` }} />
      </div>
      <div className="chat-messages">
        {messages.map((m, i) => (
          <div key={i} className={`chat-bubble-row ${m.role}`}>
            {m.role === 'ai' && <div className="chat-avatar ai">AI</div>}
            <div className={`chat-bubble ${m.role}`}>{m.text}</div>
            {m.role === 'user' && <div className="chat-avatar user">You</div>}
          </div>
        ))}
        <div ref={bottomRef} />
      </div>

      {!allDone ? (
        <div className="chat-input-row">
          <textarea
            className="chat-input"
            rows={2}
            placeholder="Type your answer…"
            value={inputVal}
            onChange={e => setInputVal(e.target.value)}
            onKeyDown={handleKeyDown}
          />
          <button
            className="btn btn-primary btn-sm chat-send-btn"
            onClick={sendMessage}
            disabled={!inputVal.trim()}
          >
            <Send size={14} />
          </button>
        </div>
      ) : (
        <div className="chat-done-row">
          <button className="btn btn-primary btn-sm" onClick={handleSubmit} disabled={submitting}>
            {submitting ? <><Loader2 size={14} className="spinner" /> Submitting…</> : <><Send size={14} /> Submit Answers</>}
          </button>
        </div>
      )}
    </div>
  );
}

// ─── Edit form ────────────────────────────────────────────────────────────────
function EditForm({ ticket, token, onSaved, onCancel }) {
  const [form, setForm] = useState({
    title: ticket.title || '',
    description: ticket.description || '',
    environment: ticket.environment || '',
    stepsRaw: (ticket.steps_to_reproduce || []).join('\n'),
    expected_result: ticket.expected_result || '',
    actual_result: ticket.actual_result || '',
    priority: ticket.priority || 'Medium',
    severity: ticket.severity || 'Medium',
    module_name: ticket.module_name || '',
    fix_version: ticket.fix_version || '',
    affected_version: ticket.affected_version || '',
    due_date: ticket.due_date || '',
    client: ticket.client || '',
    epic: ticket.epic || '',
    sprint: ticket.sprint || '',
  });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const sf = (f) => (e) => setForm(p => ({ ...p, [f]: e.target.value }));

  const handleSave = async (e) => {
    e.preventDefault();
    setSaving(true);
    setError(null);
    const steps = form.stepsRaw ? form.stepsRaw.split('\n').map(s => s.trim()).filter(Boolean) : undefined;
    const payload = {
      title:            form.title            || undefined,
      description:      form.description      || undefined,
      environment:      form.environment      || undefined,
      steps_to_reproduce: steps?.length ? steps : undefined,
      expected_result:  form.expected_result  || undefined,
      actual_result:    form.actual_result    || undefined,
      priority:         form.priority         || undefined,
      severity:         form.severity         || undefined,
      module_name:      form.module_name      || undefined,
      fix_version:      form.fix_version      || undefined,
      affected_version: form.affected_version || undefined,
      due_date:         form.due_date         || undefined,
      client:           form.client           || undefined,
      epic:             form.epic             || undefined,
      sprint:           form.sprint           || undefined,
    };
    try {
      const res = await fetch(`${API_BASE}/tickets/${ticket.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(parseApiError(await res.json()));
      onSaved(await res.json());
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <form className="edit-form" onSubmit={handleSave}>
      <div className="slide-meta-grid slide-meta-grid-2">
        <div className="slide-meta-item">
          <span className="slide-meta-label">Priority</span>
          <select className="slide-select" value={form.priority} onChange={sf('priority')}>
            {PRIORITY_OPTIONS.map(p => <option key={p}>{p}</option>)}
          </select>
        </div>
        <div className="slide-meta-item">
          <span className="slide-meta-label">Severity</span>
          <select className="slide-select" value={form.severity} onChange={sf('severity')}>
            {SEVERITY_OPTIONS.map(s => <option key={s}>{s}</option>)}
          </select>
        </div>
      </div>

      <div className="slide-meta-grid">
        <div className="slide-meta-item">
          <span className="slide-meta-label">Module</span>
          <input className="slide-select" value={form.module_name} onChange={sf('module_name')} placeholder="Module…" />
        </div>
        <div className="slide-meta-item">
          <span className="slide-meta-label">Fix Version</span>
          <input className="slide-select" value={form.fix_version} onChange={sf('fix_version')} placeholder="v1.0…" />
        </div>
        <div className="slide-meta-item">
          <span className="slide-meta-label">Affected Ver.</span>
          <input className="slide-select" value={form.affected_version} onChange={sf('affected_version')} placeholder="v0.9…" />
        </div>
        <div className="slide-meta-item">
          <span className="slide-meta-label">Due Date</span>
          <input type="date" className="slide-select" value={form.due_date} onChange={sf('due_date')} />
        </div>
      </div>

      <div className="slide-meta-grid slide-meta-grid-2">
        <div className="slide-meta-item">
          <span className="slide-meta-label">Epic</span>
          <input className="slide-select" value={form.epic} onChange={sf('epic')} placeholder="No epic" />
        </div>
        <div className="slide-meta-item">
          <span className="slide-meta-label">Sprint</span>
          <input className="slide-select" value={form.sprint} onChange={sf('sprint')} placeholder="No sprint" />
        </div>
      </div>

      <div className="slide-section">
        <div className="slide-section-label">Title <span style={{color:'var(--error)'}}>*</span></div>
        <input className="slide-select" style={{fontSize:'0.875rem'}} value={form.title} onChange={sf('title')} required />
      </div>

      <div className="slide-section">
        <div className="slide-section-label">Description <span style={{color:'var(--error)'}}>*</span></div>
        <textarea className="slide-textarea" rows={4} value={form.description} onChange={sf('description')} required />
      </div>

      <div className="slide-section">
        <div className="slide-section-label">Environment</div>
        <textarea className="slide-textarea" rows={2} value={form.environment} onChange={sf('environment')} placeholder="Browser, OS, version…" />
      </div>

      <div className="slide-section">
        <div className="slide-section-label">Steps to Reproduce</div>
        <textarea className="slide-textarea" rows={3} value={form.stepsRaw} onChange={sf('stepsRaw')} placeholder={"1. Go to…\n2. Click…"} />
        <span className="form-hint">One step per line</span>
      </div>

      <div className="slide-two-col">
        <div className="slide-section">
          <div className="slide-section-label">Expected</div>
          <textarea className="slide-textarea" rows={3} value={form.expected_result} onChange={sf('expected_result')} />
        </div>
        <div className="slide-section">
          <div className="slide-section-label">Actual</div>
          <textarea className="slide-textarea" rows={3} value={form.actual_result} onChange={sf('actual_result')} />
        </div>
      </div>

      {error && <div className="slide-error"><AlertCircle size={14} /> {error}</div>}

      <div className="slide-actions">
        <button type="button" className="btn btn-ghost btn-sm" onClick={onCancel}>Cancel</button>
        <button type="submit" className="btn btn-primary btn-sm" disabled={saving}>
          {saving ? <><Loader2 size={14} className="spinner" /> Saving…</> : 'Save Changes'}
        </button>
      </div>
    </form>
  );
}

// ─── Main Dashboard ───────────────────────────────────────────────────────────
export default function DashboardPage({ token, onLogout }) {
  const location = useLocation();
  const navigate = useNavigate();

  const [tickets, setTickets]           = useState([]);
  const [activeTicket, setActiveTicket] = useState(null);
  const [showNewPanel, setShowNewPanel] = useState(false);
  const [editMode, setEditMode]         = useState(false);
  const [form, setForm]                 = useState(EMPTY_FORM);
  const [attachments, setAttachments]   = useState([]);
  const [loading, setLoading]           = useState(false);
  const [error, setError]               = useState(null);
  // Track which submitted tickets had image attachments — so OCR step is only shown when relevant
  const [ticketHadAttachments, setTicketHadAttachments] = useState({});
  const fileInputRef = useRef(null);

  const sf = (f) => (e) => setForm(p => ({ ...p, [f]: e.target.value }));

  // Central fetch wrapper: auto-logout on 401 (expired/invalid token)
  const apiFetch = useCallback(async (url, options = {}) => {
    const res = await fetch(url, {
      ...options,
      headers: { Authorization: `Bearer ${token}`, ...options.headers },
    });
    if (res.status === 401) {
      onLogout?.();
      throw new Error('Session expired — please log in again.');
    }
    return res;
  }, [token, onLogout]);

  const fetchTickets = useCallback(async () => {
    try {
      const res = await apiFetch(`${API_BASE}/tickets/`);
      if (res.ok) setTickets(await res.json());
    } catch (e) { if (e.message !== 'Session expired — please log in again.') console.error(e); }
  }, [apiFetch]);

  const fetchTicketDetails = useCallback(async (id, silent = false) => {
    try {
      if (!silent) setLoading(true);
      const res = await apiFetch(`${API_BASE}/tickets/${id}`);
      if (res.ok) {
        const data = await res.json();
        setActiveTicket(data);
        setEditMode(false);
      }
    } catch (e) { if (!silent) console.error(e); }
    finally { if (!silent) setLoading(false); }
  }, [apiFetch]);

  useEffect(() => { fetchTickets(); }, [fetchTickets]);

  // Poll while processing
  useEffect(() => {
    if (!activeTicket || !['processing', 'pending'].includes(activeTicket.status)) return;
    const id = setInterval(() => {
      fetchTicketDetails(activeTicket.id, true);
      fetchTickets();
    }, 2500);
    return () => clearInterval(id);
  }, [activeTicket, fetchTicketDetails, fetchTickets]);

  // Attach files
  const handleFiles = (files) => {
    Array.from(files).forEach(file => {
      if (!file.type.startsWith('image/')) return;
      if (file.size > 5 * 1024 * 1024) { alert(`${file.name} exceeds 5 MB.`); return; }
      const reader = new FileReader();
      reader.onload = e => setAttachments(prev => [...prev, { name: file.name, base64: e.target.result, preview: e.target.result }]);
      reader.readAsDataURL(file);
    });
  };

  // Submit new ticket
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    const steps = form.stepsRaw ? form.stepsRaw.split('\n').map(s => s.trim()).filter(Boolean) : undefined;
    const payload = {
      title: form.title, description: form.description,
      environment: form.environment || undefined,
      steps_to_reproduce: steps?.length ? steps : undefined,
      expected_result: form.expected_result || undefined,
      actual_result: form.actual_result || undefined,
      priority: form.priority || undefined, severity: form.severity || undefined,
      module_name: form.module_name || undefined, fix_version: form.fix_version || undefined,
      affected_version: form.affected_version || undefined, due_date: form.due_date || undefined,
      client: form.client || undefined, epic: form.epic || undefined, sprint: form.sprint || undefined,
      attachments: attachments.length ? attachments.map(a => a.base64) : undefined,
    };
    try {
      const res = await apiFetch(`${API_BASE}/tickets/submit`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(parseApiError(await res.json()));
      const data = await res.json();
      const hadAttachments = attachments.length > 0;
      // Backend returns immediately — open detail panel right away, polling handles the rest
      setForm(EMPTY_FORM); setAttachments([]); setShowNewPanel(false);
      if (data.ticket_id) {
        if (hadAttachments) setTicketHadAttachments(prev => ({ ...prev, [data.ticket_id]: true }));
        fetchTickets();
        fetchTicketDetails(data.ticket_id);
      } else {
        fetchTickets();
      }
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  };

  const openTicket = useCallback((id) => { setEditMode(false); fetchTicketDetails(id); }, [fetchTicketDetails]);
  const closePanel = () => { setActiveTicket(null); setEditMode(false); setError(null); };

  // Handle opening ticket from navigation state (e.g. from All Tickets page)
  useEffect(() => {
    if (location.state?.openTicketId) {
      const ticketId = location.state.openTicketId;
      openTicket(ticketId);
      // Clear navigation state so that refresh or going back doesn't trigger open again
      navigate(location.pathname, { replace: true, state: {} });
    }
  }, [location.state, location.pathname, openTicket, navigate]);

  const transitionStatus = async (newStatus) => {
    if (!activeTicket) return;
    setLoading(true);
    setError(null);
    try {
      const res = await apiFetch(`${API_BASE}/tickets/${activeTicket.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus }),
      });
      if (!res.ok) throw new Error(parseApiError(await res.json()));
      const updated = await res.json();
      setActiveTicket(updated);
      fetchTickets();
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  };

  const ticketsInCol = (col) => tickets.filter(t => col.statuses.includes(t.status));

  // Analytics — computed live from tickets
  const inProgressCount = tickets.filter(t => ['pending', 'needs_clarification', 'processing'].includes(t.status)).length;
  const doneCount       = tickets.filter(t => t.status === 'completed').length;
  const failedCount     = tickets.filter(t => ['failed', 'closed', 'duplicate_found'].includes(t.status)).length;
  const withScore       = tickets.filter(t => t.score != null);
  const avgScore        = withScore.length > 0 ? Math.round(withScore.reduce((s, t) => s + t.score, 0) / withScore.length) : null;
  const totalAffected   = tickets.reduce((s, t) => s + (t.affected_count || 1), 0);

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className="dashboard-wrapper">
      {/* Top bar */}
      <div className="dashboard-topbar">
        <h2>Dashboard</h2>
        <button className="btn btn-primary btn-sm" onClick={() => { setShowNewPanel(true); setActiveTicket(null); }}>
          <Plus size={15} /> New Ticket
        </button>
      </div>

      {/* Analytics bar */}
      <div className="analytics-bar">
        <div className="stat-card">
          <div className="stat-card-icon-row"><TicketCheck size={14} /></div>
          <span className="stat-card-value">{tickets.length}</span>
          <span className="stat-card-label">Total Tickets</span>
        </div>
        <div className="stat-card stat-inprogress">
          <div className="stat-card-icon-row"><Clock size={14} /></div>
          <span className="stat-card-value">{inProgressCount}</span>
          <span className="stat-card-label">In Progress</span>
        </div>
        <div className="stat-card stat-done">
          <div className="stat-card-icon-row"><CheckCheck size={14} /></div>
          <span className="stat-card-value">{doneCount}</span>
          <span className="stat-card-label">Done</span>
        </div>
        <div className="stat-card stat-failed">
          <div className="stat-card-icon-row"><AlertOctagon size={14} /></div>
          <span className="stat-card-value">{failedCount}</span>
          <span className="stat-card-label">Failed / Closed</span>
        </div>
        <div className="stat-card stat-score">
          <div className="stat-card-icon-row"><TrendingUp size={14} /></div>
          <span className="stat-card-value">{avgScore != null ? `${avgScore}` : '—'}</span>
          <span className="stat-card-label">Avg Quality Score</span>
        </div>
        <div className="stat-card stat-affected">
          <div className="stat-card-icon-row"><Users size={14} /></div>
          <span className="stat-card-value">{totalAffected}</span>
          <span className="stat-card-label">Users Affected</span>
        </div>
      </div>

      {/* Kanban board */}
      <div className="kanban-board">
        {COLUMNS.map(col => (
          <div key={col.id} className="kanban-col">
            <div className="kanban-col-header">
              <span className="kanban-col-dot" data-col={col.id} />
              <span className="kanban-col-title" title={col.hint}>{col.label}</span>
              <span className="kanban-col-count">{ticketsInCol(col).length}</span>
            </div>
            <div className="kanban-col-body">
              {ticketsInCol(col).length === 0 && (
                <div className="kanban-empty"><Inbox size={18} /><span>No tickets here</span></div>
              )}
              {ticketsInCol(col).map(t => (
                <div
                  key={t.id}
                  className={`kanban-card ${activeTicket?.id === t.id ? 'active' : ''}`}
                  onClick={() => openTicket(t.id)}
                >
                  <div className="kanban-card-top">
                    <span className="kanban-card-id">TK-{String(t.id).padStart(3, '0')}</span>
                    <Badge status={t.status} />
                  </div>
                  <div className="kanban-card-title">{t.title}</div>
                  <div className="kanban-card-meta">
                    {t.priority && <span className={`badge priority-${t.priority.toLowerCase()}`}>{t.priority}</span>}
                    {t.severity && <span className="kanban-card-severity">{t.severity}</span>}
                    {t.affected_count > 1 && (
                      <span className="badge badge-affected" title={`${t.affected_count} users reported this`}>
                        <Users size={9} /> {t.affected_count}
                      </span>
                    )}
                    <span className="kanban-card-date">
                      {new Date(t.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* ── New Issue slide panel ── */}
      {showNewPanel && (
        <div className="slide-overlay" onClick={() => setShowNewPanel(false)}>
          <div className="slide-panel" onClick={e => e.stopPropagation()}>
            <div className="slide-panel-header">
              <div className="slide-panel-title-row">
                <FileText size={15} /><span>NEW TICKET</span>
                <span className="slide-panel-type">TASK</span>
              </div>
              <button className="btn btn-ghost btn-icon" onClick={() => { setShowNewPanel(false); setForm(EMPTY_FORM); setAttachments([]); }}>
                <X size={16} />
              </button>
            </div>

            <form className="slide-form" onSubmit={handleSubmit}>
              <input className="slide-title-input" placeholder="Ticket title" value={form.title} onChange={sf('title')} required />

              <div className="slide-meta-grid">
                <div className="slide-meta-item">
                  <span className="slide-meta-label">PRIORITY</span>
                  <select className="slide-select" value={form.priority} onChange={sf('priority')}>
                    {PRIORITY_OPTIONS.map(o => <option key={o}>{o}</option>)}
                  </select>
                </div>
                <div className="slide-meta-item">
                  <span className="slide-meta-label">SEVERITY</span>
                  <select className="slide-select" value={form.severity} onChange={sf('severity')}>
                    {SEVERITY_OPTIONS.map(o => <option key={o}>{o}</option>)}
                  </select>
                </div>
                <div className="slide-meta-item slide-meta-span-2">
                  <span className="slide-meta-label">DUE DATE</span>
                  <input type="date" className="slide-select" value={form.due_date} onChange={sf('due_date')} />
                </div>
              </div>

              <div className="slide-meta-grid">
                {[['MODULE','module_name','Module…'],['FIX VERSION','fix_version','v1.0…'],['AFFECTED VER.','affected_version','v0.9…'],['CLIENT','client','No client']].map(([lbl,f,ph]) => (
                  <div key={f} className="slide-meta-item">
                    <span className="slide-meta-label">{lbl}</span>
                    <input className="slide-select" placeholder={ph} value={form[f]} onChange={sf(f)} />
                  </div>
                ))}
              </div>

              <div className="slide-section">
                <div className="slide-section-label"><FileText size={13} /> Description <span style={{color:'var(--error)'}}>*</span></div>
                <textarea className="slide-textarea" rows={4} placeholder="Add a detailed description…" value={form.description} onChange={sf('description')} required />
              </div>

              <div className="slide-section">
                <div className="slide-section-label">Environment</div>
                <textarea className="slide-textarea" rows={2} placeholder="Browser, Build, OS, etc." value={form.environment} onChange={sf('environment')} />
              </div>

              <div className="slide-section">
                <div className="slide-section-label">Steps to Reproduce</div>
                <textarea className="slide-textarea" rows={3} placeholder={"1. Go to…\n2. Click on…\n3. Observe that…"} value={form.stepsRaw} onChange={sf('stepsRaw')} />
                <span className="form-hint">One step per line</span>
              </div>

              <div className="slide-two-col">
                <div className="slide-section">
                  <div className="slide-section-label"><Eye size={13} /> Expected Behavior</div>
                  <textarea className="slide-textarea" rows={3} placeholder="What should happen…" value={form.expected_result} onChange={sf('expected_result')} />
                </div>
                <div className="slide-section">
                  <div className="slide-section-label"><AlertTriangle size={13} /> Actual Behavior</div>
                  <textarea className="slide-textarea" rows={3} placeholder="What actually happens…" value={form.actual_result} onChange={sf('actual_result')} />
                </div>
              </div>

              {/* Attachments */}
              <div className="slide-section">
                <div className="slide-section-label"><Paperclip size={13} /> Attachments</div>
                <div className="attach-dropzone" onClick={() => fileInputRef.current?.click()} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); handleFiles(e.dataTransfer.files); }}>
                  <Paperclip size={15} /><span>Upload Images</span>
                  <span className="attach-hint">Max 5MB per file, images only</span>
                </div>
                <input ref={fileInputRef} type="file" accept="image/*" multiple style={{ display: 'none' }} onChange={e => handleFiles(e.target.files)} />
                {attachments.length > 0 && (
                  <div className="attach-previews">
                    {attachments.map((a, i) => (
                      <div key={i} className="attach-thumb">
                        <img src={a.preview} alt={a.name} />
                        <button type="button" className="attach-remove" onClick={() => setAttachments(p => p.filter((_,j) => j !== i))}><X size={11} /></button>
                        <span className="attach-name">{a.name}</span>
                      </div>
                    ))}
                  </div>
                )}
                {attachments.length > 0 && <p className="attach-ocr-note">AI will OCR {attachments.length} image{attachments.length > 1 ? 's' : ''} to extract ticket details.</p>}
              </div>

              {error && <div className="slide-error"><AlertCircle size={14} /> {error}</div>}

              <div className="slide-actions">
                <button type="button" className="btn btn-ghost btn-sm" onClick={() => { setShowNewPanel(false); setForm(EMPTY_FORM); setAttachments([]); }}>Cancel</button>
                <button type="submit" className="btn btn-primary btn-sm" disabled={loading}>
                  {loading ? <><Loader2 size={14} className="spinner" /> Creating…</> : <><Send size={14} /> Submit Ticket</>}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ── Ticket detail slide panel ── */}
      {activeTicket && !showNewPanel && (
        <div className="slide-overlay" onClick={closePanel}>
          <div className="slide-panel slide-panel-detail" onClick={e => e.stopPropagation()}>
            {/* Header */}
            <div className="slide-panel-header">
              <div className="slide-panel-title-row">
                <span className="kanban-card-id">TK-{String(activeTicket.id).padStart(3, '0')}</span>
                <Badge status={activeTicket.status} />
                {activeTicket.score != null && <span className="detail-score">Score: {activeTicket.score}/100</span>}
              </div>
              <div style={{ display: 'flex', gap: '0.25rem', alignItems: 'center' }}>
                {/* Reopen — for closed/failed/duplicate */}
                {['closed', 'failed', 'duplicate_found'].includes(activeTicket.status) && (
                  <button
                    className="btn btn-ghost btn-sm"
                    title="Reopen ticket for re-audit"
                    onClick={() => transitionStatus('pending')}
                    disabled={loading}
                  >
                    <RefreshCcw size={13} /> Reopen
                  </button>
                )}
                {/* Close — for anything not already closed/processing */}
                {!['processing', 'pending', 'closed', 'failed', 'duplicate_found'].includes(activeTicket.status) && (
                  <button
                    className="btn btn-ghost btn-sm"
                    title="Close this ticket"
                    onClick={() => transitionStatus('closed')}
                    disabled={loading}
                  >
                    <Archive size={13} /> Close
                  </button>
                )}
                {/* Edit — not while AI is running */}
                {!['processing', 'pending', 'completed', 'closed'].includes(activeTicket.status) && (
                  <button
                    className="btn btn-ghost btn-icon"
                    title={editMode ? 'Cancel edit' : 'Edit ticket'}
                    onClick={() => setEditMode(p => !p)}
                  >
                    {editMode ? <RotateCcw size={15} /> : <Pencil size={15} />}
                  </button>
                )}
                <button className="btn btn-ghost btn-icon" onClick={closePanel}><X size={16} /></button>
              </div>
            </div>

            <div className="slide-detail-body">
              {loading && <div className="detail-loading"><Loader2 size={18} className="spinner" /></div>}

              {!loading && editMode ? (
                <EditForm
                  ticket={activeTicket}
                  token={token}
                  onSaved={(updated) => { setActiveTicket(updated); setEditMode(false); fetchTickets(); }}
                  onCancel={() => setEditMode(false)}
                />
              ) : !loading && (
                <>
                  <h2 className="detail-ticket-title">{activeTicket.title}</h2>

                  <div className="detail-meta-row">
                    {activeTicket.priority  && <span className={`badge priority-${activeTicket.priority.toLowerCase()}`}>{activeTicket.priority}</span>}
                    {activeTicket.severity  && <span className="badge badge-neutral">{activeTicket.severity}</span>}
                    {activeTicket.affected_count > 1 && (
                      <span className="badge badge-affected">
                        <Users size={10} /> {activeTicket.affected_count} users affected
                      </span>
                    )}
                    {activeTicket.module_name && <span className="badge badge-neutral">{activeTicket.module_name}</span>}
                    {activeTicket.sprint    && <span className="badge badge-neutral">Sprint: {activeTicket.sprint}</span>}
                    {activeTicket.epic      && <span className="badge badge-neutral">Epic: {activeTicket.epic}</span>}
                    {activeTicket.due_date  && <span className="badge badge-neutral">Due: {activeTicket.due_date}</span>}
                  </div>

                  <DS title="Description"><div className="detail-description">{activeTicket.description}</div></DS>

                  {activeTicket.environment && (
                    <DS title="Environment"><div className="detail-field-value">{activeTicket.environment}</div></DS>
                  )}
                  {activeTicket.steps_to_reproduce?.length > 0 && (
                    <DS title="Steps to Reproduce">
                      <ol className="detail-steps-list">
                        {activeTicket.steps_to_reproduce.map((s, i) => <li key={i}>{s}</li>)}
                      </ol>
                    </DS>
                  )}
                  {(activeTicket.expected_result || activeTicket.actual_result) && (
                    <div className="detail-two-col">
                      {activeTicket.expected_result && <DS title="Expected Behavior"><div className="detail-field-value">{activeTicket.expected_result}</div></DS>}
                      {activeTicket.actual_result   && <DS title="Actual Behavior"><div className="detail-field-value">{activeTicket.actual_result}</div></DS>}
                    </div>
                  )}
                  {activeTicket.ocr_text && (
                    <DS title="OCR / Attachment Analysis"><pre className="ocr-text-block">{activeTicket.ocr_text}</pre></DS>
                  )}
                  {(activeTicket.findings?.length > 0 || activeTicket.missing_information?.length > 0) && (
                    <div className="detail-two-col">
                      {activeTicket.findings?.length > 0 && (
                        <DS title="Audit Findings">
                          <ul className="detail-bullet-list">{activeTicket.findings.map((f,i) => <li key={i}>{f}</li>)}</ul>
                        </DS>
                      )}
                      {activeTicket.missing_information?.length > 0 && (
                        <DS title="Missing Details">
                          <ul className="detail-bullet-list warning">{activeTicket.missing_information.map((m,i) => <li key={i}>{m}</li>)}</ul>
                        </DS>
                      )}
                    </div>
                  )}

                  {/* Status blocks */}
                  {activeTicket.status === 'pending' && (() => {
                    const hasOcr = ticketHadAttachments[activeTicket.id] || !!activeTicket.ocr_text;
                    return (
                      <div className="status-block status-block-analyzing">
                        <div className="status-block-title"><Loader2 size={15} className="spinner" /> AI is analysing your ticket…</div>
                        <div className="analyzing-steps">
                          {hasOcr && <span className="analyzing-step active">Reading image attachments (OCR)</span>}
                          <span className={`analyzing-step ${hasOcr ? '' : 'active'}`}>Auditing ticket quality</span>
                          <span className="analyzing-step">Routing to next step</span>
                        </div>
                        <p className="analyzing-note">This usually takes 5–15 seconds. You can close this panel — we&apos;ll update the board automatically.</p>
                      </div>
                    );
                  })()}
                  {activeTicket.status === 'processing' && (
                    <div className="status-block status-block-processing">
                      <div className="status-block-title"><Loader2 size={15} className="spinner" /> Processing pipeline…</div>
                      <div className="analyzing-steps">
                        <span className="analyzing-step done">Audit passed</span>
                        <span className="analyzing-step active">Rewriting ticket</span>
                        <span className="analyzing-step">Checking duplicates</span>
                        <span className="analyzing-step">Publishing to GitHub</span>
                      </div>
                    </div>
                  )}
                  {activeTicket.status === 'failed' && (
                    <div className="status-block status-block-failed">
                      <div className="status-block-title"><XCircle size={15} /> Pipeline Failed</div>
                      <p style={{fontSize:'0.8125rem',color:'var(--text-secondary)'}}>{activeTicket.error_message || 'An error occurred.'}</p>
                    </div>
                  )}
                  {activeTicket.status === 'duplicate_found' && (
                    <div className="status-block status-block-duplicate">
                      <div className="status-block-title"><ClipboardList size={15} /> Duplicate Detected</div>
                      <p style={{fontSize:'0.8125rem',color:'var(--text-secondary)'}}>Matches an existing ticket with ≥ 85% similarity.</p>
                    </div>
                  )}
                  {activeTicket.status === 'completed' && (
                    <div className="status-block status-block-completed">
                      <div className="status-block-title"><CheckCircle2 size={15} /> Completed</div>
                      {activeTicket.github_issue_url && (
                        <a href={activeTicket.github_issue_url} target="_blank" rel="noreferrer" className="github-link">
                          <GitBranch size={14} /> View GitHub Issue #{activeTicket.github_issue_number} <ExternalLink size={12} />
                        </a>
                      )}
                      {activeTicket.rewritten_title && (
                        <div className="rewritten-block">
                          <h4>Rewritten Ticket</h4>
                          <div className="rewritten-body">
                            <h5>{activeTicket.rewritten_title}</h5>
                            <pre>{activeTicket.rewritten_description}</pre>
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {activeTicket.status === 'closed' && (
                    <div className="status-block status-block-closed">
                      <div className="status-block-title"><Archive size={15} /> Closed</div>
                      <p style={{fontSize:'0.8125rem',color:'var(--text-secondary)'}}>
                        This ticket was manually closed. Use <strong>Reopen</strong> to send it back for re-audit.
                      </p>
                    </div>
                  )}

                  {/* Chatbot clarification */}
                  {activeTicket.status === 'needs_clarification' && activeTicket.questions?.length > 0 && (
                    <div className="status-block status-block-clarification">
                      <div className="status-block-title"><AlertTriangle size={15} /> Clarification Required</div>
                      <p style={{fontSize:'0.8125rem',color:'var(--text-secondary)',marginBottom:'0.75rem'}}>
                        Answer the questions below to improve ticket quality. You can also <button className="btn-link" onClick={() => setEditMode(true)}>edit the ticket directly</button>.
                      </p>
                      <ClarificationChat
                        ticket={activeTicket}
                        token={token}
                        onDone={() => { fetchTickets(); fetchTicketDetails(activeTicket.id); }}
                        onError={setError}
                      />
                      {error && <div className="slide-error" style={{marginTop:'0.5rem'}}><AlertCircle size={14} /> {error}</div>}
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Tiny detail section wrapper
function DS({ title, children }) {
  return (
    <div className="detail-section">
      <div className="detail-section-title">{title}</div>
      {children}
    </div>
  );
}
